
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Fixed fixedContainer;
	private global::Gtk.ProgressBar progressBar;
	private global::Gtk.Button skipButton;
	private global::Gtk.Entry answerText;
	private global::Gtk.Label translationLabel;
	private global::Gtk.Label spanishLabel;
	private global::Gtk.Button checkButton;
	private global::Gtk.DrawingArea drawingArea;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.TooltipMarkup = "next";
		this.WidthRequest = 40;
		this.HeightRequest = 40;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedContainer = new global::Gtk.Fixed ();
		this.fixedContainer.Name = "fixedContainer";
		this.fixedContainer.HasWindow = false;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.progressBar = new global::Gtk.ProgressBar ();
		this.progressBar.Name = "progressBar";
		this.fixedContainer.Add (this.progressBar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.progressBar]));
		w1.X = 128;
		w1.Y = 254;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.skipButton = new global::Gtk.Button ();
		this.skipButton.CanFocus = true;
		this.skipButton.Name = "skipButton";
		this.skipButton.UseUnderline = true;
		this.skipButton.Label = global::Mono.Unix.Catalog.GetString ("Skip");
		this.fixedContainer.Add (this.skipButton);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.skipButton]));
		w2.X = 179;
		w2.Y = 207;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.answerText = new global::Gtk.Entry ();
		this.answerText.CanFocus = true;
		this.answerText.Name = "answerText";
		this.answerText.IsEditable = true;
		this.answerText.InvisibleChar = '•';
		this.fixedContainer.Add (this.answerText);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.answerText]));
		w3.X = 125;
		w3.Y = 131;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.translationLabel = new global::Gtk.Label ();
		this.translationLabel.Name = "translationLabel";
		this.translationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("zu  Deutsch");
		this.fixedContainer.Add (this.translationLabel);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.translationLabel]));
		w4.X = 46;
		w4.Y = 133;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.spanishLabel = new global::Gtk.Label ();
		this.spanishLabel.Name = "spanishLabel";
		this.spanishLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Spanish");
		this.fixedContainer.Add (this.spanishLabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.spanishLabel]));
		w5.X = 165;
		w5.Y = 83;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.checkButton = new global::Gtk.Button ();
		this.checkButton.CanFocus = true;
		this.checkButton.Events = ((global::Gdk.EventMask)(256));
		this.checkButton.Name = "checkButton";
		this.checkButton.UseUnderline = true;
		this.checkButton.Label = global::Mono.Unix.Catalog.GetString ("Check");
		this.fixedContainer.Add (this.checkButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.checkButton]));
		w6.X = 174;
		w6.Y = 170;
		// Container child fixedContainer.Gtk.Fixed+FixedChild
		this.drawingArea = new global::Gtk.DrawingArea ();
		this.drawingArea.WidthRequest = 100;
		this.drawingArea.HeightRequest = 100;
		this.drawingArea.Name = "drawingArea";
		this.fixedContainer.Add (this.drawingArea);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixedContainer [this.drawingArea]));
		w7.X = 29;
		w7.Y = 16;
		this.Add (this.fixedContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.skipButton.Clicked += new global::System.EventHandler (this.skipClicked);
		this.answerText.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.onKeyPressed);
		this.checkButton.Clicked += new global::System.EventHandler (this.checkClicked);
		this.drawingArea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.drawingAreaExposed);
	}
}
